abbr -a g git
abbr -a ga "git add"
abbr -a gaa "git add --all"
abbr -a gst "git status -sb"
abbr -a gcm "git commit -m"
abbr -a gco "git checkout"
abbr -a gb "git branch"
abbr -a gl "git log --oneline --graph --decorate"
abbr -a gp "git push"
abbr -a gpl "git pull --rebase"
abbr -a glog "git log --oneline --graph --all --decorate"
abbr -a gd "git diff"
abbr -a gdc "git diff --cached"
abbr -a grs "git restore"
abbr -a grh "git reset HEAD"
abbr -a grhh "git reset --hard HEAD"
abbr -a gsta "git stash push"
abbr -a gstp "git stash pop"
abbr -a gstl "git stash list"
abbr -a gstd "git stash drop"
abbr -a gco- "git checkout -"
abbr -a gpsup "git push -u origin HEAD"
abbr -a gcf "git config --list"
abbr -a gcam "git commit -am"
abbr -a gcan "git commit --amend --no-edit"
abbr -a gsur "git submodule update --recursive --remote"
abbr -a gclean "git clean -fd"

abbr -a ghpr "gh pr"
abbr -a ghprc "gh pr create"
abbr -a ghprm "gh pr merge"
abbr -a ghco "gh pr checkout"
abbr -a ghis "gh issue"
abbr -a ghl "gh issue list"
abbr -a ghr "gh repo"
abbr -a ghrv "gh repo view"
abbr -a ghw "gh repo view --web"
abbr -a ghs "gh status"
abbr -a ghrc "gh repo create"
abbr -a ghrcl "gh repo clone"
